/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author ernid
 */
public class Inicio extends javax.swing.JFrame {
    
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    Image imagenCursor_normal = toolkit.getImage(getClass().getResource("/img/icono_raton_normal.png"));
    Image imagenCursor_clic = toolkit.getImage(getClass().getResource("/img/icono_raton_clic.png"));
    Cursor cursor_normal = toolkit.createCustomCursor(imagenCursor_normal , new Point(this.getX(),this.getY()), "img");
    Cursor cursor_clic = toolkit.createCustomCursor(imagenCursor_clic , new Point(this.getX(),this.getY()), "img");
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_comenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siete y media");
        setCursor(cursor_normal);
        setMaximumSize(new java.awt.Dimension(805, 627));
        setMinimumSize(new java.awt.Dimension(805, 627));
        setPreferredSize(new java.awt.Dimension(805, 627));
        setResizable(false);
        setSize(new java.awt.Dimension(805, 627));
        getContentPane().setLayout(null);

        bt_comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comenzar_off.png"))); // NOI18N
        bt_comenzar.setBorder(null);
        bt_comenzar.setBorderPainted(false);
        bt_comenzar.setContentAreaFilled(false);
        bt_comenzar.setCursor(cursor_clic);
        bt_comenzar.setFocusPainted(false);
        bt_comenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_comenzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_comenzarMouseExited(evt);
            }
        });
        bt_comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comenzarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_comenzar);
        bt_comenzar.setBounds(340, 470, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_comenzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_comenzarMouseEntered
        bt_comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comenzar_on.png"))); 
    }//GEN-LAST:event_bt_comenzarMouseEntered

    private void bt_comenzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_comenzarMouseExited
        bt_comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comenzar_off.png"))); 
    }//GEN-LAST:event_bt_comenzarMouseExited

    private void bt_comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comenzarActionPerformed
            this.setVisible(false);
            Principal principal = new Principal();
            principal.setVisible(true);
    }//GEN-LAST:event_bt_comenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_comenzar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
