/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author ernid
 */
public class Victoria extends javax.swing.JFrame {

    /**
     * Creates new form Victoria
     */
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    Image imagenCursor_normal = toolkit.getImage(getClass().getResource("/img/icono_raton_normal.png"));
    Image imagenCursor_clic = toolkit.getImage(getClass().getResource("/img/icono_raton_clic.png"));
    Cursor cursor_normal = toolkit.createCustomCursor(imagenCursor_normal , new Point(this.getX(),this.getY()), "img");
    Cursor cursor_clic = toolkit.createCustomCursor(imagenCursor_clic , new Point(this.getX(),this.getY()), "img");
    public Victoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_nota = new javax.swing.JLabel();
        bt_repetir = new javax.swing.JButton();
        lb_imagenVictoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡ VICTORIA ! ");
        setCursor(cursor_normal);
        setMaximumSize(new java.awt.Dimension(419, 558));
        setMinimumSize(new java.awt.Dimension(419, 558));
        setResizable(false);
        setSize(new java.awt.Dimension(419, 558));
        getContentPane().setLayout(null);

        lb_nota.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lb_nota.setForeground(new java.awt.Color(255, 255, 255));
        lb_nota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_nota.setText("Nota: Al volver a jugar tendrás la partida anterior detras de la nueva partida");
        lb_nota.setToolTipText("");
        getContentPane().add(lb_nota);
        lb_nota.setBounds(20, 480, 400, 40);

        bt_repetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volvera_jugar_off.png"))); // NOI18N
        bt_repetir.setBorder(null);
        bt_repetir.setBorderPainted(false);
        bt_repetir.setContentAreaFilled(false);
        bt_repetir.setCursor(cursor_clic);
        bt_repetir.setFocusPainted(false);
        bt_repetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_repetirActionPerformed(evt);
            }
        });
        getContentPane().add(bt_repetir);
        bt_repetir.setBounds(140, 430, 140, 50);

        lb_imagenVictoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/victoria.png"))); // NOI18N
        getContentPane().add(lb_imagenVictoria);
        lb_imagenVictoria.setBounds(0, 0, 420, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_repetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_repetirActionPerformed
        this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_bt_repetirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Victoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Victoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_repetir;
    private javax.swing.JLabel lb_imagenVictoria;
    private javax.swing.JLabel lb_nota;
    // End of variables declaration//GEN-END:variables
}
